name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest  # Runs in an Ubuntu runner (VM)
    steps:
      - name: Clone repo in runner
        uses: actions/checkout@v4  # a pre-built action (with version)

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements-test.txt

      - name: Lint  # Could also run in a separate job or separate workflow
        run: flake8 src tests

      - name: Run tests
        run: pytest
